service: youtube-video-downloader
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: sa-east-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource:
            - '*'

functions:
  downloader:
    handler: downloader.handler
    environment:
      VIDEOS_BUCKET_NAME:
        Ref: VideosBucket
    events:
      - httpApi:
          path: /download
          method: post
    
resources:
  Resources:
    VideosBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        LifecycleConfiguration:
          Rules:
            - Status: Enabled
              ExpirationInDays: 1
              Prefix: 'videos/'
    
    VideosBucketAllowPublicReadPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: 
          Ref: VideosBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement: 
            - Effect: Allow
              Action: 
                - 's3:GetObject'
              Resource:
                Fn::Join:
                  - '/'
                  - - !GetAtt VideosBucket.Arn
                    - '*'
              Principal: '*'

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  